version: '3'
services:
  backend: &app_base
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - /app/vendor
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
