default: &default
  include_webpacks:
    - name: webpacker_engine
      path: package/webpacker_engine

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
